### PR TITLE
LPS-76524 ProjectTemplateCustomizer

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test

**Comment by gamerson** [comment]
cc @christopherbryanboyd @david-truong

**Comment by gamerson** [comment]
ci:reopen

**Comment by gamerson** [comment]
ci:retest

**Comment by christopherbryanboyd** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
hey @Ithildir  i'm not going to make this as retest since the project-templates tests passed.

**Comment by Ithildir** [comment]
It's fine @gamerson, I already reviewed it and I'm going to send it to Brian today!

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/53726.

**Pull request closed without merging**
