### PR TITLE
LPS-79734

### PR DESCRIPTION
**Pull request by petershin**
Hi Andrea!  There's a few ways to fix this issue.  I'm not sure if this is the best way.

Here's a link to the CI failure: [test-portal-acceptance-pullrequest-batch(master)/wsdd-builder-jdk8](https://github.com/brianchandotcom/liferay-portal/pull/57251#issuecomment-382065050)

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:reopen

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:reopen

**Comment by Ithildir** [comment]
Hi @petershin,
Let's talk about it next Monday! 😊

**Pull request closed without merging**
