### PR TITLE
LPS-63740

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:stop

**Comment by Ithildir** [comment]
Hi!
Shouldn't we give this pull to the documentation team, so they can be sure it's following the Markdown and README conventions (if we have them)?

**Comment by david-truong** [comment]
@codyhoag has gone through it once but didn't check for markdown conventions.

**Comment by codyhoag** [comment]
cc/ @sez11a @jhinkey

Brian just created a ticket ([LRDOCS-2580](https://issues.liferay.com/browse/LRDOCS-2580)) for creating a standardized format for README files in `liferay-portal`. The docs team will need to come up with this format (does not exist currently), so we can begin reviewing these sorts of requests accordingly. 

I've performed a general wordsmithing (via Google Doc), but this file will likely change once a standard README format has been created. It's up to you guys and Brian if it's OK to publish now and review with the standard format later, or wait until we've agreed on the formatting before publishing.

**Comment by Ithildir** [comment]
For now, I can just fix the small Markdown errors that I found and send it to Brian!

**Comment by jhinkey** [comment]
FYI - I just drafted a guidelines file README_FILE_GUIDELINES.markdown, submitted in https://github.com/sez11a/liferay-portal/pull/6 for https://issues.liferay.com/browse/LRDOCS-2580

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/39848.

**Pull request closed without merging**
