### PR TITLE
LPS-77343 rough draft of Target Platform Plugin README

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
cc @codyhoag  

Hey Cody could you help do an edit of this? https://github.com/Ithildir/liferay-portal/pull/905/commits/7c2e7309d06d10202d6edf69fff1c52b7c29261a  

its the README for the TP plugin

**Comment by gamerson** [comment]
ci:test

**Comment by codyhoag** [comment]
@gamerson sure thing. I'll review once Andrea is finished with it.

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/56009.

**Pull request closed without merging**
