### PR TITLE
LPS-65362

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Looks like this one will give ModuleVersionNotFoundExceptions all over the place...

Should republish before making the changes to build.gradle?

**Comment by Ithildir** [comment]
Hi!
If the symbolic name changed, it's a different artifact, which is still unpublished. I'm afraid we have to convert all those dependencies to project dependencies.

**Comment by hhuijser** [comment]
@Ithildir 

Is that a matter of simply doing this: https://github.com/liferay/liferay-portal/commit/6cbd9b0dc3822714cbefc095da7d62d418440048

Or is there more required?

**Comment by Ithildir** [comment]
I think just that one!

**Comment by hhuijser** [comment]
Okay, I'll resend...

**Pull request closed without merging**
