### PR TITLE
LPS-75049

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:reopen

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:help

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:stop

**Comment by petershin** [comment]
ci:test

**Comment by Ithildir** [comment]
Testing it in https://github.com/Ithildir/liferay-portal/pull/960.

**Pull request closed without merging**
