### PR TITLE
LPS-69706 part 2

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
@Ithildir here is part-2

**Comment by gamerson** [comment]
ci:stop

**Comment by gamerson** [comment]
no need to run ci tests, we know these will fail

**Comment by gamerson** [comment]
@Ithildir  for this pull to succeed we need `com.liferay.portal.tools.theme.builder` 1.0.3 to be published.

**Comment by gamerson** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:reopen

**Pull request closed without merging**
