### PR TITLE
COMMERCE-299

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
https://issues.liferay.com/browse/COMMERCE-299

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
Hey @Ithildir, could you please help me with reviewing this PR? The first half of the commits should look familiar as it was already reviewed by you. :) 

Sorry, I know it a pile of code to review :/ Thanks in advance!

Zoli

/cc @marco-leo

**Comment by Ithildir** [comment]
Hi @ZoltanTakacs and @marco-leo,
Do you know why Brian didn't want to merge your previous pulls? It'd be easier for me to just review your code once we know Brian will look at it and merge it.

**Comment by ZoltanTakacs** [comment]
Hey @Ithildir, I asked him but I didn't get any response from him unfortunately.. :( see https://github.com/brianchandotcom/liferay-portal/pull/54552#issuecomment-361947508

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/56017.

**Pull request closed without merging**
