### PR TITLE
LPS-70092 Update npm shrinkwrap

### PR DESCRIPTION
**Pull request by brunobasto**
Hey @Ithildir, @juliocamarero found an issue when using metal-cli 2 and the `replaceSoyTranslation` task. Basically, the soy compiler uses a different argument delimiter. Also, they don't encapsulate the replacement logic inside `goog.getMsg` anymore so we can just use their logic. No need to replace the variables ourselves. 

Basically, what this PR does is:

if `goog.getMsg` is called passing 3 arguments, assume it's metal-cli 1.x and it will go through the logic we already have.

If `goog.getMsg` is called with 2 arguments, assume it's metal-2.x and just replace `{` by `\x01` and leave the arguments replacement logic to the soy compiler.

I didn't test it because I'm not sure how to make my changes take effect in the build process, but it should be a simple change.

Let me know what you think. Thx!

/cc @jbalsas

### CODE REVIEW

**Comment by brunobasto** [comment]
Hey @Ithildir,

Also, I'd like to discuss how can we also update the `*.soy.js.map` files. Since we are changing the number of lines, the source maps becomes outdated.

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/46139. How should we change the `*.soy.js.map` files?

**Comment by jbalsas** [comment]
Hey @Ithildir... maybe here? https://github.com/liferay/liferay-portal/blob/master/modules/sdk/gradle-plugins-soy/src/main/java/com/liferay/gradle/plugins/soy/SoyTranslationPlugin.java#L65-L66

**Comment by Ithildir** [comment]
Is the same replacement logic okay?

**Comment by jbalsas** [comment]
I think so, yeah...

**Comment by Ithildir** [comment]
Okay, I'll work on it today!

**Comment by jbalsas** [comment]
But maybe it's not, since it may be escaped and/or minified... could you verify when you're working on it?

**Comment by Ithildir** [comment]
Yeah, sure!

**Comment by brunobasto** [comment]
Maybe we could just call https://www.npmjs.com/package/gulp-sourcemaps

**Comment by Ithildir** [comment]
Hi @brunobasto and @jbalsas!
I just started to look into the source maps update, but I don't think that simply doing a replace in the `.js.map` files will be enough. What about the `names` array and that `mappings` string?

I tried to generate the sourcemap with the Closure Compiler, but it's complaining about namespaces like `soy` not being provided...

Any ideas?

**Comment by brunobasto** [comment]
Hey Andrea, I was quickly looking into it, but it may be not very straightforward because we have more than one transformation steps. This project aims to help with that, but looks like it's a work in progress: https://github.com/Rich-Harris/sorcery/blob/master/README.md

**Comment by Ithildir** [comment]
So I guess we're not doing anything about it for now, right?

**Comment by brunobasto** [comment]
Yeah. Let's leave it be for now. I'd say this is not high priority. I can
look into it when I get back.

Thx, Andrea

**Pull request closed without merging**
