### PR TITLE
LPS-56692

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
can you help me upgrade css builder to use the new param sass.generate.source.map

**Comment by Ithildir** [comment]
Sure! I'm currently fixing a problem in `gradle-plugins-css-builder`, so the project is already open :smile: 

And what about running the CSS Builder in the `classes` dir? Should we do this as well?

**Comment by david-truong** [comment]
I would like to but i haven't gotten around to trying it yet.  Someone asked me to also add the precision as a configuration today: https://issues.liferay.com/browse/LPS-60172

**Comment by Ithildir** [comment]
Should I send the pull directly to Brian or you want it back? :blush:

**Comment by david-truong** [comment]
To Brian please.. please leave source maps disabled by default for now.  It
needs more work (it should be working though) but I just want this code in
so I can start working working on the precision fix for the UI team.

On Wed, Nov 4, 2015 at 8:51 PM, Andrea Di Giorgi <notifications@github.com>
wrote:

> Should I send the pull directly to Brian or you want it back? [image:
> :blush:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Ithildir/liferay-portal/pull/125#issuecomment-153938823>
> .
>



-- 
David Truong
Product Manager
david.truong@liferay.com
Liferay, Inc

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/31839 :blush:

**Pull request closed without merging**
