### PR TITLE
LPS-68497 Autogenerated

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @Ithildir 

I'm sending this to you because I don't know what's happening with this PR. I desperately need your help :-)

This is a pretty straightforward import of two legacy plugins (twitter-portlet and my-subscriptions-portlet) into the main repository. The problem is that sometimes the build fails to resolve the Ivy dependencies; in the CI it always fails, and when I build it locally it eventually works (but the first time I get consistent failures). The thing that puzzles me is that, without making any changes, if I try a couple of `ant all` it successfully builds.

I've tried to mimic the build scripts in other similar plugins (e.g. private/apps/lcs in EE) but I get the same results. Could you take a look at this in case I missed something obvious? I really have no idea what's happening here :-(

Thanks!

/cc @sergiogonzalez

### CODE REVIEW

**Comment by adolfopa** [comment]
rebased and push-force'd

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
Ok, so this last error is the good one: while it has the dependencies correctly declared in the Ivy file, it fails to find them at compile time.

**Comment by Ithildir** [comment]
Ok, I'm looking into it! If I find the problem, should I send the pull to Brian?

**Comment by Ithildir** [comment]
Hi @adolfopa,

It's my fault, I wasn't testing the `.gitignore` files for Ant plugins outside of Git subrepos 😞

https://github.com/brianchandotcom/liferay-portal/pull/43963 adds that check, so, if you run `ant test-class -Dtest.class=ModulesStructureTest` from `portal-kernel`, it will tell you what `.gitignore` files to add to your branch and what to write in them.

You'll also have to commit the Ivy dependency jars in the 2 plugins, so CI won't call Ivy. That's how we're doing for Ant plugins.

**Comment by adolfopa** [comment]
Thanks a lot @Ithildir !

**Comment by Ithildir** [comment]
FYI, I had to re-send my pull at https://github.com/brianchandotcom/liferay-portal/pull/43976.

**Pull request closed without merging**
