### PR TITLE
SYNC-1607

### PR DESCRIPTION
**Pull request by shinnlok**

### CODE REVIEW

**Comment by shinnlok** [comment]
force pushed. ci:retest

**Comment by shinnlok** [comment]
ci:stop ci:retest

**Comment by Ithildir** [comment]
Thank you! :blush:

I'll wait until we finally push your OAuth pull before forwarding this one... It'll be an interesting, because `oauth-api` is in `ee-7.0.x`, but we have a CE module that requires it. I'll probably have to ask Brian about it!

**Comment by shinnlok** [comment]
Yup, wasn't sure what to do with it. Hopefully you can figure something out. :)

Thank!

**Pull request closed without merging**
