### PR TITLE
LPS-73070 Generates package-lock files (auto-generated)

### PR DESCRIPTION
**Pull request by Robert-Frampton**

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
@jbalsas

**Comment by jbalsas** [comment]
ci:reopen

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by Ithildir** [comment]
Hi @Robert-Frampton!
Do you think we should first send https://github.com/Ithildir/liferay-portal/pull/730/commits/da8b81efe7af77c384ce5485142c4e165a2e047e and `npm-shrinkwrap.json` for everything, including private and read-only repos? If this new version is compatible with the Node we're using, I think it'll be easier to switch to Node 8 if all the modules are already using compatible dependencies.

What do you think?

**Comment by jbalsas** [comment]
Hey @Robert-Frampton, @Ithildir, I've resent this as https://github.com/ithildir/liferay-portal/pull/769.

I've kept the node change contained within the `foundation` app. I guess you decided to try in there first? Let's try to push this asap so it doesn't conflict anymore.

As soon as this is good to go, I can start preparing additional PRs for the different apps.

Thanks!

**Pull request closed without merging**
