### PR TITLE
LPS-67552 we can now check private-package since portlet template has been fixed

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
ci:retest

**Comment by Ithildir** [comment]
Last night I started the review :sweat_smile: I guess I'll wait until we have all the commits :smile:

**Comment by gamerson** [comment]
@Ithildir it should all be there now.  all of the tests pass on PRTester now.

**Comment by Ithildir** [comment]
Good, thank you!!

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/43211.

**Pull request closed without merging**
