### PR TITLE
Update project template tokens with latest service builder fixes

### PR DESCRIPTION
**Pull request by lawrence-lee**
Please let this finish. If passes, can we publish a new workspace plugin?

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test

**Comment by lawrence-lee** [comment]
ci:stop

**Comment by lawrence-lee** [comment]
ci:test:modules-unit-jdk8

**Comment by christopherbryanboyd** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lawrence-lee** [comment]
ci:test:modules-unit-jdk8

**Comment by Ithildir** [comment]
ci:reopen

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/57890.

**Pull request closed without merging**
