### PR TITLE
LPS-73858

### PR DESCRIPTION
**Pull request by holatuwol**
We backported com.liferay.ant.sync.dir.jar to every branch, so we need to maintain JDK 6 compatibility.

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:reopen

**Comment by holatuwol** [comment]
ci:retest

**Comment by Ithildir** [comment]
I'm sorry @holatuwol, I don't have time to review your pull today 😞 I'll work on it next week!

Thanks!!

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/50684.

**Pull request closed without merging**
