### PR TITLE
LPS-80474 Update "ant nightly" logic to automatically use the rigth download URL for the private branches

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-80474

Hi Andrea,

I'm sending the changes we discussed over Slack last week. Please let me know if you have any concerns.

Thanks,
Tibor

### CODE REVIEW

**Comment by lipusz** [comment]
Such a milestone (1000th PR!) :-D :+1:

**Comment by lipusz** [comment]
ci:test

**Comment by lipusz** [comment]
Also sent a PR for master-private

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/58085.

**Pull request closed without merging**
