### PR TITLE
LPS-61405 Javadocs for modules should only contain classes specified by the bnd "Export-Package" property

### PR DESCRIPTION
**Pull request by CAustin582**

### CODE REVIEW

**Comment by CAustin582** [comment]
@jhinkey This will tell gradle's javadocs task to define its includes according to what the bnd lists as export packages. Submitted to @Ithildir for review.

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/33479

**Comment by jhinkey** [comment]
+1

**Comment by jhinkey** [comment]
@CAustin582 - This works well. Just tried it out. Thanks!

**Pull request closed without merging**
