### PR TITLE
SYNC-1590

### PR DESCRIPTION
**Pull request by dejuknow**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:stop

**Comment by dejuknow** [comment]
Hi Andrea, BChan asked me to send this PR to you (see https://github.com/brianchandotcom/liferay-portal/pull/38886). I'm adding the java plugin and repos list so I can compile sync-engine as a subproject from the main liferay-sync-ee gradle project. This will only be used for testing/development purposes.

**Comment by Ithildir** [comment]
Hi! I'm sorry, I've never seen liferay-sync-ee... How is it structured?

**Comment by dejuknow** [comment]
github.com/liferay/liferay-sync-ee. I'm guessing you can't see it because it's a private repo, but this is what our build.gradle looks like: https://gist.github.com/dejuknow/ea773481a73d135ab7ccd638aad90eaa.

We use this to build the Liferay Sync client for Mac and Windows.

**Comment by dejuknow** [comment]
Normally, we push sync-engine to Maven, but for testing sake, it's convenient to build sync-engine from source instead of always pushing to Maven.

**Comment by Ithildir** [comment]
So you import the `sync-engine` from `modules` to `liferay-sync-ee`, then build it from there, right? Why don't you use [configuration injection](https://docs.gradle.org/current/userguide/multi_project_builds.html#sec:cross_project_configuration) in your `build.gradle`? This way, we don't have to change the `build.gradle` script inside `modules/util/sync-engine` :blush:

Something like this:

```gradle
project(":sync-engine") {
	apply plugin: "java"

	repositories {
		mavenLocal()

		maven {
			url "http://cdn.repository.liferay.com/nexus/content/groups/public"
		}
	}
}
```

Even better:

```gradle
project(":sync-engine") {
	apply plugin: "com.liferay.defaults.plugin"
	apply plugin: "com.liferay.plugin"
}
```

You have to add a `buildscript` dependency to `com.liferay:com.liferay.gradle.plugins:latest.release` in order for this second snippet to work. Basically, you're applying the same plugins we use inside `modules`, so you'll automatically have the same exact default configuration.

What do you think?

**Comment by dejuknow** [comment]
That's really cool. I got it working with the second snippet. Thanks for your help, Andrea!

**Comment by Ithildir** [comment]
Glad it worked! :blush:

**Pull request closed without merging**
