### PR TITLE
LPS-72705

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey Andrea, can you check I'm not removing/adding stuff I shouldn't?
You can send to Brian if it looks okay to you.

Thanks!

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
Hi @hhuijser,
I don't think you can remove those `Private-Package` in the `*-test` modules: they're used by the Arquillian integration (or something like that) for the integration tests. As you can see, those tests failed.

**Comment by hhuijser** [comment]
@Ithildir was afraid of that.. I'll exclude those

**Pull request closed without merging**
