### PR TITLE
LPS-78873 liferay-npm-bundler assumes both dependencies and devDependencies are in package.json

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test

**Comment by gamerson** [comment]
cc @izaera

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/56250.

**Comment by Ithildir** [comment]
ci:stop Testing on Brian's pull.

**Pull request closed without merging**
