### PR TITLE
IDE-4081 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
@Ithildir  tests were run and passed here: https://github.com/gamerson/liferay-portal/pull/143#issuecomment-396670807

**Comment by gamerson** [comment]
@cody-hoag

@Ithildir  can you ask brian to publish everything (all archetypes and plugins) (including ProjectTemplates 4.0.1) after this ?

**Comment by Ithildir** [comment]
ci:test

**Comment by gamerson** [comment]
ci:reopen

**Comment by gamerson** [comment]
ci:test:releveant

**Comment by gamerson** [comment]
ci:test:relevant

**Comment by gamerson** [comment]
ci:test:relevant

**Comment by gamerson** [comment]
@Ithildir  it passed!

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/60365.

**Pull request closed without merging**
