### PR TITLE
LPS-82590 remove snapshot from test

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @Ithildir  we need this to be merged, before we can test this:
https://github.com/brianchandotcom/liferay-portal/pull/60499#issuecomment-398450034

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/60598.

**Pull request closed without merging**
