### PR TITLE
LPS-79496 SF

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:relevant

**Comment by gamerson** [comment]
ci:test

**Comment by Ithildir** [comment]
@gamerson and @christopherbryanboyd, I just sent https://github.com/brianchandotcom/liferay-portal/pull/57572 which checks `liferayVersion` with `=` in several places, like [here](https://github.com/brianchandotcom/liferay-portal/pull/57572/files#diff-827f8456e7233ca2fe16706e810622d4R36). Can you please resend this pull once the other pull is merged, applying https://github.com/Ithildir/liferay-portal/pull/979/commits/f155b4f8dd2a7b585d92863bbe42e1daaa078560 everywhere? Thanks!

**Comment by christopherbryanboyd** [comment]
Hey @Ithildir  no problem, I'll work on that as soon as the other pull is merged!

**Comment by christopherbryanboyd** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
