### PR TITLE
LPS-64991 Test

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:stop

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:stop

**Comment by Ithildir** [comment]
ci:retest

**Comment by jpince** [comment]
@Ithildir don't worry about the smoke failures, these are error messages that were ignored in a later commit.

I noticed these two failures in your pulls since the very beginning, see [this gist](https://gist.github.com/jpince/6106bbbf4291583d8c196292469cba3f), hopefully that helps

**Comment by Ithildir** [comment]
Thank you so much @jpince! Maybe there's a problem in `opensocial-portlet`, I'll try to disable it and retest!

**Comment by Ithildir** [comment]
ci:retest

**Pull request closed without merging**
