### PR TITLE
LPS-67021 - Task cache

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
Hey Andrea, I'm working on LPS-67075 with staging team (it's all about the .lar file). but by the moment this error is important to be solved.

Thanks

**Comment by Ithildir** [comment]
Hi Marcos! The task cache seems not to be ok, but I can regenerate it, no problem. Should I keep the theme disabled?

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/41505.

**Comment by marcoscv-work** [comment]
@Ithildir yes, the theme should fix the problems with the lar importation before to be enabled, we are working on that.

thanks a lot

**Pull request closed without merging**
