### PR TITLE
LPS-68979 Update shrinkwrap.json

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @Ithildir, in this PR you can check the empty copied folders in gradle in case you want to clean it!

You can see it in the modules/apps/foundation/frontend-js/frontend-js-~~web~~metal-web module 😉 

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @Ithildir, you can see the folders in the `modules/apps/foundation/frontend-js/frontend-js-metal-web` module. Sorry for the confusion! 👼

**Comment by Ithildir** [comment]
No problem! I'm going to make the changes to `gradle-plugins-js-transpiler` and send them to Brian. Then, when it's merged, you can go ahead and send this pull!

**Comment by Ithildir** [comment]
ci:stop

**Comment by Ithildir** [comment]
Sent to https://github.com/jbalsas/liferay-portal/pull/647.

**Pull request closed without merging**
