### PR TITLE
LPS-69139 add new m2e lifecycle

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @Ithildir  the soy-maven-plugin still doesn't have the lifecycles and I haven't sent the pull yet because I haven't been able to test it yet, but I will do that tomorrow.

**Comment by Ithildir** [comment]
For now, I sent https://github.com/Ithildir/liferay-portal/pull/663/commits/5c0bad2ca88008999d70754fe67f76a40fbc98ab to https://github.com/brianchandotcom/liferay-portal/pull/48331. I'll work on moving the Soy Maven plugin to `modules/third-party` today, then I'll send the rest 😊

**Comment by Ithildir** [comment]
ci:reopen

**Comment by Ithildir** [comment]
ci:stop

**Comment by Ithildir** [comment]
I also sent https://github.com/Ithildir/liferay-portal/pull/663/commits/10a9373760e0d4f10676d93b0b375c1595019fce to https://github.com/brianchandotcom/liferay-portal/pull/48367. I'll fix the rest once the new `portal-tools-soy-builder` is published.

**Comment by Ithildir** [comment]
Sent to https://github.com/gamerson/liferay-portal/pull/132.

**Pull request closed without merging**
