### PR TITLE
LPS-74315 setup common excludes list

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
cc @david-truong

**Comment by gamerson** [comment]
hey @Ithildir  don't send this to brian yet.  we have some more changes we want to send and have brian publish all the changes at once and set major versino to 2.0.  Dave has a host of other changes we would like to make.

**Comment by gamerson** [comment]
but those changes will come in followup pulls

**Comment by Ithildir** [comment]
Sent to https://github.com/gamerson/liferay-portal/pull/22.

**Pull request closed without merging**
