### PR TITLE
LPS-69706 part 1

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
cc @david-truong

**Comment by Ithildir** [comment]
ci:stop

**Comment by Ithildir** [comment]
@gamerson, should I do the same in `portal-tools-theme-builder`? I see it still uses the deprecated class...

**Comment by gamerson** [comment]
Doh I forgot that part, sending now.

**Comment by gamerson** [comment]
@Ithildir pushed!

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/46026.

**Pull request closed without merging**
