### PR TITLE
LPS-77875

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:test

**Comment by Ithildir** [comment]
😱 Did you really change the Java code of all these plugins?

**Comment by petershin** [comment]
@Ithildir - I'm sorry Andrea. The rule I followed from before is to run `installCache updateFileVersions` whenever any file within an app was changed.

I'll run `installCache updateFileVersions` on modules that have Java code changes and resend Mon morning.

**Pull request closed without merging**
