### PR TITLE
LPS-65362

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@Ithildir 

There is a bunch more incorrect Bundle-SymbolicName, but want you to review these first.

Not sure about if I should have changed "com.liferay.comment.page.comments.web" PageCommentsWebUpgrade.java

**Comment by Ithildir** [comment]
Hi!
Shouldn't we call it `comment-page-comments-web`? It's a portlet, so AFAIK we should use the `-web` prefix... Unless there's a different naming logic I'm totally unaware of :sweat_smile:

**Comment by hhuijser** [comment]
@Ithildir 

I am simply deriving from the directory name.
Does that mean that the directory should end with "-web" for that one?
If not, "calculating" the correct name would be fairly complicated...

**Comment by Ithildir** [comment]
I'm sure @brianchandotcom can tell us exactly what the pattern is, but AFAIK a module directory ends in "-web" if it's a portlet.

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/39175.

**Pull request closed without merging**
