### PR TITLE
LPS-68405 add m2e lifecycle mappings

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @Ithildir  i have not gotten these templates to actually work for me yet.  I can't download the node_modules in china.  I will be home in US on Thursday and I will try again.  So if you want to, I can test this again at that time.

**Comment by gamerson** [comment]
If you want brian to merge it that is ok, but don't publish it yet until I have a chance to try it on Thursday

**Comment by Ithildir** [comment]
Hi @gamerson!
That's okay, we can wait :) Also, maybe we'll be able to update the Metal dependency and avoid having the `.gitattributes` file inside the archetype.

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/48667.

**Pull request closed without merging**
