### PR TITLE
LPS-76201 frontend code review

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
cc @brunobasto  @christopherbryanboyd  I've sent the new pull here.  Thanks Bruno for the frontend review help!

**Comment by gamerson** [comment]
ci:test

**Comment by Ithildir** [comment]
ci:stop @gamerson, there's a compile error, I'll fix it 😊

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/54263.

**Comment by christopherbryanboyd** [comment]
Awesome, thanks guys!

**Pull request closed without merging**
