### PR TITLE
Workspace to use GA3

### PR DESCRIPTION
**Pull request by lawrence-lee**
https://issues.liferay.com/browse/LPS-67656

@Ithildir I think those are all the files I needed. Please let me know if I left anything else out!

Thank you!

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:stop

**Comment by lawrence-lee** [comment]
ci:stop

**Comment by lawrence-lee** [comment]
ci:stop

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/43444.

**Pull request closed without merging**
