### PR TITLE
pull-request-38242

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@Ithildir see https://github.com/brianchandotcom/liferay-portal/pull/38242

Thx.

**Comment by JorgeFerrer** [comment]
Hey @Ithildir, 

It seems that without this, there is no reasonable way to upgrade an existing installation to Liferay 7. I'm not sure how we could release GA1 without this, but I would appreciate if you could prioritize this pull to make sure it can make it to GA2.

/cc @david-truong @achaparro @brianchandotcom @sez11a

**Comment by Ithildir** [comment]
Hi @JorgeFerrer! I almost finished doing the basic SF that Brian asked, I'll forward the pull this morning.

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/38734.

**Comment by JorgeFerrer** [comment]
Awesome, thanks so much.

**Pull request closed without merging**
