### PR TITLE
Update project templates

### PR DESCRIPTION
**Pull request by lawrence-lee**
I'm unable to run the tests locally

Pushed from https://github.com/lawrence-lee/liferay-portal/pull/68

### CODE REVIEW

**Comment by lawrence-lee** [comment]
@Ithildir It looks like the Project Templates Tests passed. I'm going to do some more testing on my end. I'll let you know when its good to go. Thanks!

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/52619.

**Comment by Ithildir** [comment]
Oh sorry @lawrence-lee, I haven't seen your msg! If you're sending me a pull and you're not sure if I should forward it, please write it in the comment at the beginning of the pull 😊 Should I stop the one to Brian?

**Comment by lawrence-lee** [comment]
@Ithildir Yes Please. I'll ping you on slack once its ready

**Pull request closed without merging**
