### PR TITLE
LPS-70451 Add boilerpipe as thirdparty module

### PR DESCRIPTION
**Pull request by tomwang2011**
Hi Andrea, I am working on 3rd partying some of our lib/portal jars that involves removing some conflict classes. Can you check if this is the correct way to create a new thirdparty module and if there are anything else that needs to be added, thanks!

### CODE REVIEW

**Comment by Ithildir** [comment]
Hi @tomwang2011,
Maybe there's a simple solution using only Bnd. Is it okay if I work on it and then send it to Brian?

**Comment by tomwang2011** [comment]
hi @Ithildir yes no problem, just let me know after as I have a few other jars that require removal as well, thanks!

**Comment by Ithildir** [comment]
ci:stop

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/48440.

**Pull request closed without merging**
