### PR TITLE
Lps x jacoco gradle

### PR DESCRIPTION
**Pull request by tinatian**
Hi Andrea,

This is my changes to support jacoco in gradle, I did not use jacoco plugin since I have to make sure jacoco agent is the first java agent installed.

Could you please take a look at my code when you have time? or we can have a talk about it when you are available.

Thanks.
Tina.

### CODE REVIEW

**Comment by Ithildir** [comment]
Hi @tinatian! Unfortunately today (and probably tomorrow) I'll be too busy with the Commerce stuff to take a look at your pull 😞

**Comment by tinatian** [comment]
It's OK, no hurry, we can have a talk about it tomorrow when you have time.


Thanks Andrea!

2017-06-27 10:01 GMT-07:00 Andrea Di Giorgi <notifications@github.com>:

**Comment by Ithildir** [comment]
ci:reopen

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/49956.

**Pull request closed without merging**
