### PR TITLE
COMMERCE-276

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
Hi Andrea @Ithildir ,

I've made some changes that Brian asked ([here](https://github.com/brianchandotcom/liferay-portal/pull/54486#issuecomment-358492866)) and used the [branch](https://github.com/Ithildir/liferay-portal/commits/COMMERCE-276-pr859) where you've added the XML + JavaDoc formatters.

- Could you please review this for me? :)

Thanks!

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/54552.

**Pull request closed without merging**
