### PR TITLE
LPS-68825

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
bchan was requesting this, but since it's modifying pretty much all the build.gradle files in gradle-plugins-* I got a feeling this is a bit too aggressive.

**Comment by Ithildir** [comment]
Hi @hhuijser!
Yeah, that's definitely too much 😅 

- To solve the problem with the Gradle plugins, maybe you can limit this only to the `provided` dependencies.
- For `portal-remote-rest-extender-test` and `portal-remote-soap-extender-test`, we should try to move those dependencies in the `testIntegrationCompile` configuration instead. They're only used by test code, and it doesn't make sense to have them as `provided`.
- The biggest problems are with `portal-osgi-web-wab-generator` and `sync-engine`: they embed those `provided` dependencies via `bnd.bnd`, and so I think it matters what micro version they want. Some dependencies are `provided` because the runtime will provide them via OSGi, others are `provided` because we're embedding them in the jar via `bnd.bnd`. The first ones can have a major version, the other ones IMHO should be able to have whatever micro version they want... Maybe we should use different configurations, like [`compileOnly`](https://gradle.org/blog/compile-only-dependencies/) for the embedded dependencies, and `provided` for the other ones. But it's a big change 😕

**Comment by hhuijser** [comment]
@Ithildir 
Thanks for the feedback. Is this something you want to add to your todo list?
Seems not very urgent to me...

**Comment by Ithildir** [comment]
I sent a fix for the test dependencies at https://github.com/brianchandotcom/liferay-portal/pull/44164.

**Pull request closed without merging**
