### PR TITLE
COMMERCE-355

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
https://issues.liferay.com/browse/COMMERCE-355

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
Hi @Ithildir, 

Could you please take a look at on this PR? :) I would be glad if you can double check for SF errors.

/cc @marco-leo

Thanks,
Zoli

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by Ithildir** [comment]
ci:stop Sent to https://github.com/brianchandotcom/liferay-portal/pull/56645.

**Comment by ZoltanTakacs** [comment]
Thank you @Ithildir ! :)

**Pull request closed without merging**
