### PR TITLE
FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test

**Comment by gamerson** [comment]
ci:stop

**Comment by gamerson** [comment]
hey @lawrence-lee  and @Ithildir  we need to wait on this because IDE has found 3-4 problems with project templates that we need to update before we publish a new ProjectTemplates 4.0.0

**Comment by Ithildir** [comment]
Ok @gamerson, let me know when I can review it 😊

**Comment by Ithildir** [comment]
Hi @gamerson,
Does this pull still make sense?

**Comment by gamerson** [comment]
nope!

**Pull request closed without merging**
