### PR TITLE
LPS-634110 set outputs for build task to war file

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
ci:retest

**Comment by Ithildir** [comment]
@gamerson, what do you think about adding the war to the artifacts of the `archives` configuration instead?

**Comment by gamerson** [comment]
Sure lets do that instead.  I'll try to resend.

On Fri, Feb 19, 2016 at 1:39 PM, Andrea Di Giorgi <notifications@github.com>
wrote:

> @gamerson <https://github.com/gamerson>, what do you think about adding
> the war to the artifacts of the archives configuration instead?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Ithildir/liferay-portal/pull/253#issuecomment-186372431>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Pull request closed without merging**
