### PR TITLE
LPS-70581 update maven wrapper cause the current one can't execute on windows

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:stop

**Comment by gamerson** [comment]
ci:restart

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
ci:retest

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/50685.

**Pull request closed without merging**
