### PR TITLE
LRQA-30769 Prevent regeneration of system.packages.extra.mf during semantic versioning

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-30769

### CODE REVIEW

**Comment by pyoo47** [comment]
@Ithildir I'm expecting the semantic-versioning-jdk8 to fail this pull request test because the manifest file is missing from the zip file. It should work once this commit is combined with your changes.

**Comment by Ithildir** [comment]
ci:stop

**Comment by pyoo47** [comment]
@Ithildir I've modified this branch with new commits that should take care of the source formatting issue and provide support for modules-compile. Please replace my earlier commit in your branch with these two commits.

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/47060.

**Pull request closed without merging**
