### PR TITLE
LPS-79004 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test

**Comment by gamerson** [comment]
ci:stop

**Comment by Ithildir** [comment]
@gamerson, should I close this?

**Comment by gamerson** [comment]
just setn a new commit

**Comment by gamerson** [comment]
ci:test

**Comment by gamerson** [comment]
its ready for review now
and if all tests pass, we need brian to push ProjectTemplates 4.0.0

**Comment by Ithildir** [comment]
ci:stop Sent to https://github.com/brianchandotcom/liferay-portal/pull/56532.

**Pull request closed without merging**
