### PR TITLE
LPS-69706 don't redirect IO to current process this way we can actually see the error/output stream in the junit test logs

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:stop

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
ci:reopen

**Comment by gamerson** [comment]
ci:stop

**Comment by gamerson** [comment]
hey @Ithildir 

I see this error now on CI
```
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Could not find artifact com.liferay:com.liferay.frontend.css.common:jar:2.0.1
	at com.liferay.css.builder.maven.BuildCSSMojo.execute(BuildCSSMojo.java:88)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact com.liferay:com.liferay.frontend.css.common:jar:2.0.1
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
	at com.liferay.css.builder.maven.BuildCSSMojo._resolveArtifact(BuildCSSMojo.java:160)
	at com.liferay.css.builder.maven.BuildCSSMojo.execute(BuildCSSMojo.java:60)
	... 22 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.liferay:com.liferay.frontend.css.common:jar:2.0.1
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:434)
```

Why can't our embedded maven cli tests find that artifact?  It is on maven central.

**Comment by gamerson** [comment]
it passes for me locally, it can find that artifact.  I see it in my .m2

**Comment by gamerson** [comment]
@Ithildir we can rerun these tests once this is merged: https://github.com/Ithildir/liferay-portal/pull/579

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/46061.

**Pull request closed without merging**
