### PR TITLE
LPS-82568 Disable liferay-npm-bundler analytics

### PR DESCRIPTION
**Pull request by petershin**
Hi Andrea!

I ran `npmRunBuild` in `frontend-js-metal-web` and `frontend-js-spa-web`.  After running the task, I verified that the folder below doesn't exist:

`C:\users\liferay\AppData\Local\insight-nodejs\`

I'm running `ant all` now and will comment when the test finishes

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by Ithildir** [comment]
Great, thanks @petershin!! If you see it works with `ant all`, can you please send it to @izaera for a final check? Thanks!

**Comment by petershin** [comment]
Tests passed. 🙂 Sent a pull to Ivan: https://github.com/izaera/liferay-portal/pull/52

**Comment by petershin** [comment]
ci:stop

**Pull request closed without merging**
