### PR TITLE
LPS-59067

### PR DESCRIPTION
**Pull request by natecavanaugh**
Heya Andrea,
I'm forwarding this pull to you from @mjbradford89 as he mentioned possibly sending it to you for review since there are some gradle changes.
I've already reviewed it, but can you review the gradle stuff?
Thanks Andrea,

### CODE REVIEW

**Comment by Ithildir** [comment]
I'll review it immediately :blush: Do you want me to send it to Brian if everything is ok?

**Comment by natecavanaugh** [comment]
Yep, that'd be great. Thanks Andrea!​

**Comment by Ithildir** [comment]
I talked to @mjbradford89, maybe we can find a better solution and unzip the Lexicon files in different directories.

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/30788 :blush:

**Pull request closed without merging**
