### PR TITLE
LPS-68298 SF

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @Ithildir,

I'm sending you this to see if we can standardize https://github.com/Ithildir/liferay-portal/pull/520/commits/0939f69720c532c242eeb266aaa840e229b77e66 and https://github.com/Ithildir/liferay-portal/pull/520/commits/9a81bebf52ccf29c3e883ab029b061366a887de9 inside the `configJSModules` task.

Thanks!

### CODE REVIEW

**Comment by Ithildir** [comment]
Should we do it every time? Is there a scenario where a 3rd-party dev doesn't want to have that replacement?

**Comment by jbalsas** [comment]
I don't think so... if you run the `configJSModules` task, you want to use our built-in system and loader. To consistently do so, we need to always rename those methods.

Notwithstanding, a flag to turn this feature on and off won't hurt ;)

**Comment by Ithildir** [comment]
I see! And should I send the whole pull to Brian or just my changes to `gradle-plugins-js-module-config-generator`?

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/44438.

**Pull request closed without merging**
