### PR TITLE
LPS-75008 Test

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
@david-truong: unfortunately, it seems to fail with some obscure BridJ errors 😞

**Comment by david-truong** [comment]
did you switch the classloader at the thread level? i was getting errors with bridj until i did that

**Comment by Ithildir** [comment]
I don't think I made any significant change to [`ForkableJavaExec`](https://github.com/Ithildir/liferay-portal/blob/ea8860e9b17e827cbcf89c650a75910d3a72dbf9/modules/sdk/gradle-util/src/main/java/com/liferay/gradle/util/tasks/ForkableJavaExec.java) 🤔

**Comment by Ithildir** [comment]
Could it be caused by the fact that `ant all` runs the CSS Builder in parallel?

**Comment by david-truong** [comment]
hmm... that could be an issue...

**Comment by Ithildir** [comment]
Any particular reason why you set `java.class.path`?

**Comment by david-truong** [comment]
The jspc set its classpath that way

**Comment by david-truong** [comment]
would we be better off creating a new thread for each?

**Comment by Ithildir** [comment]
Gradle already runs CSS Builder in separate threads  (with `ForkableJavaExec`), I think that's the problem.

**Comment by david-truong** [comment]
Might need to enable it only for jspc for now until we figure out css builder

**Pull request closed without merging**
