### PR TITLE
LPS-70697 Test

### PR DESCRIPTION
**Pull request by Ithildir**
cc @pyoo47

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:stop

**Comment by Ithildir** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest - I need to rerun this pull request test so I can get the distribution bundles it creates.

**Comment by Ithildir** [comment]
@pyoo47: I was thinking... if it makes things easier for you, I can generate the `system.packages.extra.mf` directly in the root of the `portal-bootstrap` module. I'll add it to `.gitignore` and have it cleaned during `ant all`. But so, when you unzip the file from the bundle, you don't have to copy it to a different location (the `build` dir instead of the root dir). What do you think?

**Comment by pyoo47** [comment]
@lthildr I don't think it's really a big deal to unzip that file to a different location. I'll just do it the original way we discussed.

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:stop

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Pull request closed without merging**
