### PR TITLE
LPS-77875

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by Ithildir** [comment]
Thanks, sent to https://github.com/brianchandotcom/liferay-portal/pull/60051.

@petershin, I think we should also update the URLs in `liferay-plugins` and `liferay-plugins-ee`.

**Comment by petershin** [comment]
@Ithildir - Should I send these changes to you or directly to Brian?

**Comment by Ithildir** [comment]
To Brian 😊

**Pull request closed without merging**
