### PR TITLE
LPS-70036 add a portal-tools-soy-builder in order to help maven projects build soy portlets

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
cc @david-truong here is new soy builder plugin

**Comment by Ithildir** [comment]
Hi @gamerson! Did you have a look at https://github.com/eirslett/frontend-maven-plugin? Can't we use something like this to run Node from Maven?

**Comment by Ithildir** [comment]
ci:reopen

**Comment by gamerson** [comment]
hey @Ithildir my understanding is that plugin just installs node, runs npm install and other various popuplar node frameworks like grunt, bower, etc.  I didn't see how we could execute arbitrary JS files in the node_modules, since that plugin doesn't have understanding of `metal-cli` or `liferay-module-config-generator`

**Comment by gamerson** [comment]
ci:retest

**Comment by Ithildir** [comment]
@gamerson, don't you think it's possible to [contribute](https://github.com/eirslett/frontend-maven-plugin/issues/525) to that plugin? I don't remember if @david-truong started working on it... If not, I'll start reviewing your pull today or tomorrow 😊

**Comment by Ithildir** [comment]
Also, shouldn't we keep the various components (JS transpilation, module config generation and Soy) separated? What if users only need to run `metal-cli`?

**Comment by Ithildir** [comment]
Sent to https://github.com/gamerson/liferay-portal/pull/120.

**Pull request closed without merging**
