### PR TITLE
LPS-74426 simplify test

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by christopherbryanboyd** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
ci:reopen

**Comment by gamerson** [comment]
ci:retest

**Comment by Ithildir** [comment]
Hi!
If I understand correctly, this pull adds a test for the Mojo. Can you use the same approach used in `portal-tools-theme-builder`? It's way simpler 😊

**Pull request closed without merging**
