### PR TITLE
LPS-68970 improve archetypes use of maven-dependency-plugin

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
cc @jbalsas 

Hey @Ithildir  you can give initial review of this new template, but Chema needs to sign off on my changes along with verifying the output of the same build that I sent him before we send this to Brian.

**Comment by gamerson** [comment]
ci:reopen

**Comment by gamerson** [comment]
ci:retest

**Comment by jbalsas** [comment]
LGTM!

**Comment by Ithildir** [comment]
Sent to https://github.com/jbalsas/liferay-portal/pull/646.

**Pull request closed without merging**
