### PR TITLE
LPS-00000 Limit conns for npm in the build

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
just a reminder... feel free to close it and change it at will 😅

**Comment by Ithildir** [comment]
ci:reopen

**Comment by Ithildir** [comment]
Hi @csierra!

When https://github.com/brianchandotcom/liferay-portal/pull/45713 is merged you'll be able to:
1. add `nodejs.npm.args=--maxsockets 3` to your `build.*.properties`
2. run `ant setup-sdk`
3. have Gradle use that argument when it invokes NPM

**Comment by csierra** [comment]
cool! 👏 👏 👏 

thx!

**Pull request closed without merging**
