### PR TITLE
LPS-73513 invalid command for git pull in build-common.xml

### PR DESCRIPTION
**Pull request by peterborkuti**
Hi Andrea,

Could you review this?

Thank you in advance
Péter

### CODE REVIEW

**Comment by Ithildir** [comment]
Hi @peterborkuti!
Why do you need the `upstream` remote and not just clone that repo?

**Comment by peterborkuti** [comment]
Hi @Ithildir ,
Sorry, I do not understand your question.

The original command was "git pull --rebase". Because this does not work, I thought to fix the pull command. I do not know what was the original intention behind the "git pull --rebase" command, however, that is syntactically incorrect. There may be a problem if there is no "upstream" in the git local config, so probably we should check that, or try "origin" also, but that needs more complex logic.

**Comment by Ithildir** [comment]
Why doesn't `git pull --rebase` work for you? If you simply clone that repo and run the command, what's the error? It works for me 😕

**Comment by peterborkuti** [comment]
Hi @Ithildir ,

Now I know what is the root cause:

Probably your .config for git has these lines:
```
[remote "upstream"]
	url = https://github.com/liferay/liferay-binaries-cache-2017
	fetch = +refs/heads/*:refs/remotes/upstream/*
[branch "master"]
    remote = upstream
    merge = refs/heads/master
```
With this 
```
[branch "master"]
    remote = upstream
    merge = refs/heads/master
```
git pull --rebase works, however, this is not the default behaviour.
After cloning the repo, my repo does not have this setting.

**Comment by Ithildir** [comment]
No, this is my `.git/config`:

```
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
[remote "origin"]
	url = https://github.com/liferay/liferay-binaries-cache-2017.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

And I have the latest Git version: `git version 2.13.2.windows.1`.

**Comment by peterborkuti** [comment]
Hi, Yes, exactly what I suspected. This sets your default remote:
```
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

**Comment by peterborkuti** [comment]
Hi @Ithildir ,

We can close this, my colleague tried this and her git .config contains the default branch setup, so probably my git has old configuration.

Thank you and sorry.

**Pull request closed without merging**
