### PR TITLE
LPS-69188 update maven versions to latest theme.builder

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:stop

**Comment by gamerson** [comment]
@Ithildir this will have to wait until https://github.com/Ithildir/liferay-portal/pull/538 is merged.

**Comment by gamerson** [comment]
ci:stop

**Comment by Ithildir** [comment]
Sent to https://github.com/gamerson/liferay-portal/pull/105.

**Pull request closed without merging**
