### PR TITLE
LPS-77425 Fix Eclipse cycles between projects

### PR DESCRIPTION
**Pull request by arboliveira**

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/56242.

**Comment by arboliveira** [comment]
```
Caused by: org.gradle.api.GradleException: Please create marker file /opt/dev/projects/github/liferay-portal/modules/apps/collaboration/blogs/blogs-uad/.lfrbuild-portal
```

**Comment by Ithildir** [comment]
@arboliveira, yeah, nobody told me about these new modules and I don't know how they got merged... I'm sending a pull to fix it!

**Comment by Ithildir** [comment]
Actually, Brian added that file already: https://github.com/liferay/liferay-portal/commit/28a254b5418790a79d8eaa8b94cbe0210ba96693

**Pull request closed without merging**
