### PR TITLE
Make service builder versions consistent across gradle and maven

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test Please let this pull finish

**Comment by lawrence-lee** [comment]
@Ithildir I dont see any Project Template Test failures here.

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:reopen

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/57610.

**Pull request closed without merging**
