### PR TITLE
LPS-73070 Generates package-lock files (auto-generated)

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopn

**Comment by jbalsas** [comment]
Hey @Ithildir, I'm not sure about those errors, but I'm sure you know what they're about 😉

**Comment by jbalsas** [comment]
ci:reopen

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/51222.

**Pull request closed without merging**
