### PR TITLE
LPS-72471

### PR DESCRIPTION
**Pull request by shinnlok**
@Ithildir How was it decided which files to ignore for repos (compared to portal's gitignore)? Seems like a tedious process if/when we have to add to it..

### CODE REVIEW

**Comment by shinnlok** [comment]
ci:stop

**Comment by Ithildir** [comment]
@shinnlok, what Brian wants is consistency. So, if we decide to add this file, the `.gitignore` in all repos must be the same. I can take care of that, no problem.

I'm not sure Brian will like this, isn't it simply a temp file of [Node GH](http://nodegh.io/)? Can't you add it to your global `.gitignore`?

**Comment by shinnlok** [comment]
I thought the same but was wondering why it was here:

https://github.com/liferay/liferay-portal/blob/master/.gitignore#L16

**Comment by Ithildir** [comment]
Let me ask Brian. IMHO we should not add it...

**Comment by Ithildir** [comment]
Ok, he said to add it 👍

**Comment by shinnlok** [comment]
Thanks! Something else to consider..

https://github.com/liferay/liferay-portal/blob/master/.gitignore#L9-L11

I noticed someone added the file based to one of our subrepos. Are we assuming that they should be using the project based intellij ignores?

**Comment by Ithildir** [comment]
I'm sorry, I don't use Intellij so I don't know what files are generated. The Gradle `idea` task generates only a `.iml` file, is there anything else?

**Comment by shinnlok** [comment]
https://intellij-support.jetbrains.com/hc/en-us/community/posts/206915235-IPR-vs-IDEA

Do you think it makes sense to sync the two (module vs portal's gitignore) excluding the ones that are project specific.. for example, /lib/development/activation.jar.

That way there won't be a difference what gets committed regardless of where we are "developing" from.

modules/private/apps/osb-faro/osb-faro-site vs com-liferay-osb-faro-site-private

**Comment by Ithildir** [comment]
I'd rather add them to the subrepos only if they're necessary, in order to keep those files as short as possible.

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/48912.

**Pull request closed without merging**
