### PR TITLE
LPS-69706 need to add remote repositories to artifact request

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
@Ithildir   It turns out that we need these changes to the BuildCSS and BuildTheme Mojos  This is why the tests were failling when I tried to upgrade the templates to these new versions.  Previously we weren't adding the repositories into the artifact request.  

Please ask BChan to push new versions of Theme builder and Css builder (1.1.1 and 1.0.23 respectively).  Too bad we pushed broken versions before.  I wish there was a way that we could push new versions and the tests in the same pull.

**Comment by gamerson** [comment]
ci:reopen

**Comment by gamerson** [comment]
ci:retest

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/46046.

**Pull request closed without merging**
